INCLUDE(NBase)
INCLUDE(NNetwork)

FIND_LIBRARY(NUS_DBAL_LIBRARY
	NAMES ndbal-${N_VERSION}
	PATHS 
	${NUS_INSTALL_DIR}/lib 
)	

LINK_DIRECTORIES(
	${NUS_DBAL_LIBRARY_DIR}
)

INCLUDE_DIRECTORIES(
	${NUS_INCLUDE_DIR}/dbal
	${NUS_INCLUDE_DIR}/dbal/exceptions
)

LINK_LIBRARIES(
	${NUS_BASE_LIBRARY}
	${NUS_NETWORK_LIBRARY}
)