INCLUDE(NBase)
INCLUDE(NXmlDependencies)

FIND_LIBRARY(NUS_XML_LIBRARY
	NAMES nxml-${N_VERSION}
	PATHS 
	${NUS_INSTALL_DIR}/lib 
)	

LINK_DIRECTORIES(
	${NUS_XML_LIBRARY_DIR}
)

INCLUDE_DIRECTORIES(
	${NUS_INCLUDE_DIR}/xml
	${NUS_INCLUDE_DIR}/xml/exceptions
)

LINK_LIBRARIES(
	${NUS_BASE_LIBRARY}
	${NUS_XML_LIBRARY}
)