INCLUDE(NBase)
INCLUDE(NSecurityDependencies)

FIND_LIBRARY(NUS_SECURITY_LIBRARY
	NAMES nsecurity-${N_VERSION}
	PATHS 
	${NUS_INSTALL_DIR}/lib 
)	

LINK_DIRECTORIES(
	${NUS_SECURITY_LIBRARY_DIR}
)

INCLUDE_DIRECTORIES(
	${NUS_INCLUDE_DIR}/security
	${NUS_INCLUDE_DIR}/security/hash
)

LINK_LIBRARIES(
	${NUS_BASE_LIBRARY}
	${NUS_SECURITY_LIBRARY}
)