INCLUDE(NBase)
INCLUDE(NEvents)

FIND_LIBRARY(NUS_NETWORK_LIBRARY
	NAMES nnetwork-${N_VERSION}
	PATHS 
	${NUS_INSTALL_DIR}/lib
)

INCLUDE_DIRECTORIES(
	${NUS_INCLUDE_DIR}/network
	${NUS_INCLUDE_DIR}/network/exceptions
	${NUS_INCLUDE_DIR}/network/${NUS_OS_CODE_DIR}
)

LINK_DIRECTORIES(
	${NUS_NETWORK_LIBRARY_DIR}
)

LINK_LIBRARIES(
	${NUS_NETWORK_LIBRARY}
)